### ISSUE TITLE
please provide svg for logo

### ISSUE THREAD

**Issue by lkwg82** [syncthing/old-web#11]
I'd like to replace big png with svg as almost every browser supports it.

see http://caniuse.com/#search=svg

Cheers Lars

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/tree/master/assets

**Comment by calmh** [comment]
My expired AI trial to the rescue!

https://github.com/syncthing/syncthing/commit/b322b527b3e1410d8f1a6aff73dd4c38cb2a61e1
