### ISSUE TITLE
Apt commands will fail without root or sudo

### ISSUE THREAD

**Issue by ghost** [syncthing/old-web#16]
It might be good to note that `apt-key` requires sudo or root. Or perhaps the command could be displayed on-page as:

```
# Add the release PGP keys:
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
```

For adding to `/etc/apt/sources.list` a similar problem is encountered, root is required with the current command, however a sudo only option should probably be displayed on-page such as one of the following:

`echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee -a /etc/apt/sources.list`
`sudo sh -c 'echo "deb http://apt.syncthing.net/ syncthing release" >> /etc/apt/sources.list'`
`echo "deb http://apt.syncthing.net/ syncthing release" | sudo sh -c 'cat >> /etc/apt/sources.list'`

See: https://stackoverflow.com/questions/850730 and https://stackoverflow.com/questions/1584066

However an alternate (and better option in my opinion) is to add a syncthing specific sources list:

```
echo "deb http://apt.syncthing.net/ syncthing release" >/tmp/syncthing.list
sudo cp /tmp/syncthing.list /etc/apt/sources.list.d/
```

See: https://stackoverflow.com/questions/1584066

**Comment by ghost** [comment]
I would make a PR but I cannot find the source for apt.syncthing.net

**Comment by calmh** [comment]
Can't we work on the assumption that people who know how to modify package setups and so on via command line on Linux know that they need root access to do so?

> However an alternate (and better option in my opinion) is to add a syncthing specific sources list:
> echo "deb http://apt.syncthing.net/ syncthing release" >/tmp/syncthing.list
> sudo cp /tmp/syncthing.list /etc/apt/sources.list.d/

That's probably a good idea. Does this work on every recent Debianish distribution?

**Comment by ghost** [comment]
> Can't we work on the assumption that people who know how to modify package setups and so on via command line on Linux know that they need root access to do so?

Sure, I think that's a good assumption. The distinction I'm making is the 2 ways of how people gain root access. A good number of people have been trained to never use root in favor of jumping in and out of sudo. In fact the general convention for command line tutorials is to heavily discourage root usage for safety... and this generates a bias against using the root account itself.

So to that end it would be good to have a command which is sudo compatible as your current commands require the usage of the root account. (for example `>>` is executed first, so it fails if you're trying to use it with sudo) While I don't mind the current commands they will be problematic in the future without sudo compatibility of some kind.

I'm not trying to be pedantic, just trying to prevent a lot of future issues and support requests of: `I can't get this to work help me please etc etc etc` :smile: 

> That's probably a good idea. Does this work on every recent Debianish distribution?

It should, as it's a current feature of apt. Debian squeeze man page for sources.list details the sources.list.d directory: http://manpages.debian.org/cgi-bin/man.cgi?query=sources.list&apropos=0&sektion=5&manpath=Debian+6.0+squeeze&format=html&locale=en

**Comment by calmh** [comment]
You're probably right, most similar things online seem to use sudo so I guess that's what people are used to - if nothing else then just as a "this command needs root" marker.

Then there's the ever popular [curl | sh](http://curlpipesh.tumblr.com)... ;)

**Comment by ghost** [comment]
> Then there's the ever popular curl | sh... ;)

The horror... shudders... :disappointed:

**Comment by ghost** [comment]
So is the source for apt.syncthing.net here on github somewhere? If it is I'm happy to make a pull request.

**Comment by calmh** [comment]
Yeah, no, it was a quick evening hack. I'm going to clean up and put it in a repo here somewhere.

**Comment by ghost** [comment]
:+1:

**Comment by calmh** [comment]
https://github.com/syncthing/apt-web

**Comment by ghost** [comment]
For context, here's the first support request related to this issue: https://forum.syncthing.net/t/2761
