### ISSUE TITLE
Not accesible on mobile chrome

### ISSUE THREAD

**Issue by urza** [syncthing/old-web#21]
I cant access forums from my smartphone. Samsung Galaxy Note 2. Android 4.1.2 Chrome last version. 

![2015-07-23-20-37-31](https://cloud.githubusercontent.com/assets/189804/8859238/53ea597e-317c-11e5-851a-17e3d1db33b7.png)

**Comment by AudriusButkevicius** [comment]
Use https://forum.syncthing.net
Discourse was the old link which is now redirected.

Though leaving it open in case @calmh wants to fix it

**Comment by urza** [comment]
Thanks

**Comment by AudriusButkevicius** [comment]
I'll let @calmh close.

**Comment by calmh** [comment]
I don't think we've had any links towards `discourse.s.n` for quite a while. If we do, it's a bug, otherwise no I'm fine with this.
