### ISSUE TITLE
https Version with Cloudflare

### ISSUE THREAD

**Issue by davidbaumann** [syncthing/old-web#34]
Hello together,

so is cloudflare really the solution for https?
What about https://letsencrypt.org/ ?

David.

**Comment by AudriusButkevicius** [comment]
Why would we want to pay more for traffic for a static site which serves no content apart from HTML and text?

**Comment by canton7** [comment]
Https only means that caching is now harder. No one cares about the contents of the syncthing docs you're looking at)

**Comment by calmh** [comment]
The main website is cloudflare accelerated and fully https; it has a real certificate and cloudflare verifies it. The other subsites aren't secured but I'm not sure that's necessary. Also not really sure what the issue/inquiry here is really?

**Comment by calmh** [comment]
I've tweaked the config to not give certificates errors when ssl is used against docs.s.n and apt.s.n. However it's still more of an accident of the setup that there is HTTPS on those sites at all...
