### ISSUE TITLE
Why are we using cloudflare?

### ISSUE THREAD

**Issue by generalmanager** [syncthing/old-web#38]
Is there any good reason for using Cloudflare? I'm not aware that we suffered from any major DDOS attacks, but because of that the website is often a pain to use over TOR.

And people who don't want to execute sideloaded JS from everywhere by using tools like NoScript also have to jump trough hoops and allow a whole CDN, which in turn completely undermines using something like NoScript in the first place.

This is especially difficult to understand as Syncthing aims to lower peoples reliance on centralized services, but uses one of the biggest ones out there. The irony is quiet painful to say the least.

**Comment by canton7** [comment]
The Syncthing website is always going to be centralised - you can't get away from the fact that websites are centralised.

I can't speak for @calmh, but I suspect it's to cope with the high levels of traffic that the website sees. Cloudflare doesn't just provide DDOS protection: they're a general-purpose CDN.

**Comment by generalmanager** [comment]
> The Syncthing website is always going to be centralised - you can't get away from the fact that websites are centralised.

Firt of all: fully decentralized websites hosted by it's users are actually possible and there are several projects working on things like that.

But that's not the point. CDNs like Cloudflare are so widely used because of lazyness, not because they are actually needed. The web itself is designed in a decentralized manner where the idea is that everybody hosts their own website. But nowadays CDNs are becoming so important for big parts of the web that their demise/unavailability will destroy millions of websites depending on them.

> I can't speak for @calmh, but I suspect it's to cope with the high levels of traffic that the website sees. Cloudflare doesn't just provide DDOS protection: they're a general-purpose CDN.

Well from the statistics we have ~12k users. And even if every one of them and their friend visited our website daily that'd be on average 24k users in 24h, or about one user every four seconds. Even considering peak usage times, this is nothing a small VPS can't handle. And the builds are hosted on github, which leaves nothing but a few images and a little text to deliver.

**Comment by canton7** [comment]
The statistics only show a very small part of the story. Not that that invalidates anything you've said if course.

**Comment by generalmanager** [comment]
Yeah, I just wanted to have use some kind of metric so I don't have to make up the numbers. Most of the privacy concious users will have reporting disabled, but that's why I doubled the number. And realistically most current users won't visit the website frequently. Not even the contributors do so, because the community lives on the forum and the code is on github. So the people looking at the website are mostly potential new users who heard about Syncthing and want to check it out. But I thought I'd better highball it and even then the numbers are pretty pathetic and don't even warrant own hardware.

**Comment by calmh** [comment]
Because I'm lazy, because it means the page is online even if the server in my closet dies, and because it does improve load times on the page significantly for users who are not close to my closet. It's not a religious thing, so it may be changed in the future. I know it annoys Tor users somewhat, but it seems to me that using Tor for all your everyday browsing is anyway an exercise in self torture so I'm not super worried about that to be honest...

**Comment by generalmanager** [comment]
@calmh I noticed today that cloudflare now uses a modified version of the latest recaptcha with pictures. And it even works with JS disabled. This makes it a little less horrible to use over TOR for now.

Do you have some rough numbers of visitors and traffic? I think this would be interesting to see compared to the number of active devices.

**Comment by calmh** [comment]
<img width="982" alt="screen shot 2016-02-12 at 12 29 15" src="https://cloud.githubusercontent.com/assets/125426/13005748/466da974-d184-11e5-83d4-d4ba547bb8d3.png">

<img width="973" alt="screen shot 2016-02-12 at 12 30 28" src="https://cloud.githubusercontent.com/assets/125426/13005771/6f32de88-d184-11e5-9b1f-a3961eea9cb2.png">

<img width="980" alt="screen shot 2016-02-12 at 12 30 50" src="https://cloud.githubusercontent.com/assets/125426/13005773/7ae5b1d8-d184-11e5-8d9c-b1f6a0c10473.png">

~~I have no idea what min/max unique visitors over time is supposed to mean.~~ Per hour, I guess.

**Comment by generalmanager** [comment]
Wow, never thought my estimate would be this close (even tough it's unite hits vs unique visitors).
