### ISSUE TITLE
Website should force https

### ISSUE THREAD

**Issue by jonathancross** [syncthing/old-web#49]
Homepage link to "Debian / Ubuntu packages" points to: http://apt.syncthing.net

If users copy / paste commands from there they could easily be tricked into installing malware via MITM.

This is a serious security concern.

Fix:

1. [Force all insecure requests to be secure](http://serverfault.com/questions/250476/how-to-force-or-redirect-to-ssl-in-nginx#424016).
2. Fix all links to remove `http:` prefix so that users are not hitting server twice.  Eg: `//apt.syncthing.net` or force all links by explicitly using `https:` if you wahnt to be 100% sure.

**Comment by calmh** [comment]
Link fixed, also

```
$ curl -i http://apt.syncthing.net/
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.0 (Ubuntu)
Date: Wed, 16 Nov 2016 21:15:04 GMT
Content-Type: text/html
Content-Length: 194
Connection: keep-alive
Location: https://apt.syncthing.net/
```

Thanks for the prod!

**Comment by jonathancross** [comment]
Fantastic, thanks!

**Comment by AudriusButkevicius** [comment]
This potentially should be undone because of the ticket linked to this one.

**Comment by AudriusButkevicius** [comment]
Actually ignore me, we've just updated the docs.
