### ISSUE TITLE
data on data.syncthing.net seems to be missing, maybe not on purpose

### ISSUE THREAD

**Issue by grinapo** [syncthing/old-web#52]
Since Nov 8 there is no join, leave and some other data graphs. Mayb something's wedged somewhere.

**Comment by calmh** [comment]
Graphs look fine to me. There is never any leave data for the last 30 days, as we cannot tell that someone has indeed "left" until we haven't seen them for a while. We cannot peer into the future and see who might have uninstalled Syncthing today.
