### ISSUE TITLE
Some syncthing services are down

### ISSUE THREAD

**Issue by GermanCoding** [syncthing/old-web#54]
Just wanted to notify that the following sites appear to be down for me for two hours now:

- https://syncthing.net
- https://apt.syncthing.net
- https://docs.syncthing.net

Forums appear to be up.

My server in Berlin is apparently going crazy right now, because aptitude fails updating due to the syncthing repo timing out all the time. Had to disable it temporarily until it is back up.

**Comment by calmh** [comment]
Yeah, we're aware. Our infrastructure provider DigitalOcean has a storage outage that affects us.

https://status.digitalocean.com/incidents/8sk3mbgp6jgl

**Comment by calmh** [comment]
I've quickly migrated relays.s.n to a new VM. I didn't set up the geoip stuff yet. Unfortunately, it had a long DNS TTL so it might take a while to show up for people.

**Comment by calmh** [comment]
I've migrated www, docs, and apt to a new VM.

**Comment by GermanCoding** [comment]
Looks good, closing this. Oh and because I forgot that yesterday: Happy easter!
