### ISSUE TITLE
Syncthing is already in debian!

### ISSUE THREAD

**Issue by 532910** [syncthing/old-web#55]
Syncthing is already in debian.
You should point debian user to the system package first
Moreover there should be an explaination for the reason of separate repository.

**Comment by AudriusButkevicius** [comment]
Debian packages move slower than ours.

**Comment by 532910** [comment]
What is slower exactly?
Could you write an explanation on the web page https://apt.syncthing.net/

**Comment by AudriusButkevicius** [comment]
The turn around cycle. Once a new version is releassed its immediatelly available in apt, where as in debian it takes some time.

**Comment by 532910** [comment]
So it's mostly for developers, right?
Could you update the web site please, and specify that packages already in debian a the only difference is in time.

**Comment by AudriusButkevicius** [comment]
@calmh wdyt?

**Comment by AudriusButkevicius** [comment]
@c-e-p-x-u-o to be honest, docker for example still encourages to use their repos, regardless that it's shipped with debian. Why should we do otherwise?

**Comment by calmh** [comment]
There are build differences between our version and the debian version, and we are the only ones providing builds of the release candidates (obviously), etc. I think there is value in what we do.

If you want a distribution supported package you use the one from your distribution. If you want a package supported by us, you use our package.

**Comment by 532910** [comment]
What does the docker matter? It sucks!
I have not asked to drop you repository.
I just ask you to not confuse users. As when you say how to add a repository it means it's not in debian.
Please, just add a note about that the packages are already in debian, and the explanation of the difference between repos.
