### ISSUE TITLE
Fix link on badge for F-Droid

### ISSUE THREAD

**Issue by PanderMusubi** [syncthing/old-web#59]
Please, fix the link on the badge for F-Droid from

    https://f-droid.org/repository/browse/?fdid=com.nutomic.syncthingandroid

to

    https://f-droid.org/packages/com.nutomic.syncthingandroid/

**Comment by AudriusButkevicius** [comment]
You could just file a PR via the github web editor.

**Comment by PanderMusubi** [comment]
https://github.com/syncthing/website/pull/60
